# Generated by Django 2.2.4 on 2019-08-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("url", models.CharField(max_length=255)),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                ("user_agent", models.TextField()),
            ],
        )
    ]
